name: MobAbilities
main: de.robingrether.mobabilities.MobAbilities
version: 0.1.1
author: RobinGrether
depend: [iDisguise]
commands:
   mobabilities:
      description: Get abilities of different mobs.
   ma:
      description: Get abilities of different mobs.